# sudo docker-compose -f deploy/docker-compose.yml  up


version: "3"
services:
    app:
        image: flask-app
        container_name: app-backend
        build:
            context: ..
            dockerfile: deploy/Dockerfile.app     
    nginx:
        image: nginx 
        container_name: app-frontend
        build:
            context: ..
            dockerfile: deploy/Dockerfile.prod 
        ports:
            - 80:80
    db:
        image: mysql:8.0.21
        container_name: mysql-db
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../app/backend/db/entry:/docker-entrypoint-initdb.d/:ro
            - ../app/backend/db/data:/var/lib/mysql
    
