# sudo docker-compose -f deploy/docker-compose.yml  up


version: "3"
services:
    app:
        image: flask-app        # image_name
        container_name: app-backend
        build:
            context: ..
            dockerfile: deploy/Dockerfile.app
        volumes:
            - ../app/www:/app/www
        
    nginx:
        image: nginx 
        container_name: app-frontend
        ports:
            - 80:80
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ../app/www:/var/www
