#To build: sudo docker build -t registry.deti:5000/billsdivider/bdwebapp-db:11062022 -f deploy/Dockerfile.db .
#To add to registry: sudo docker push registry.deti:5000/billsdivider/bdwebapp-db:11062022

FROM mysql:8.0.21

MAINTAINER Pedro Abreu

LABEL version="1.0"

ADD app/backend/db/entry/init.sql /docker-entrypoint-initdb.d

EXPOSE 3306